# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-24 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RatingTestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating2_votes', models.PositiveIntegerField(blank=True, default=0, editable=False)),
                ('rating2_score', models.IntegerField(blank=True, default=0, editable=False)),
                ('rating_votes', models.PositiveIntegerField(blank=True, default=0, editable=False)),
                ('rating_score', models.IntegerField(blank=True, default=0, editable=False)),
            ],
        ),
    ]
